"""add_city_to_clients_suppliers

Revision ID: 1eda23ffa80d
Revises: 9d41ab2d014c
Create Date: 2026-03-28 11:35:58.568466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eda23ffa80d'
down_revision: Union[str, Sequence[str], None] = '9d41ab2d014c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
