"""add_city_columns

Revision ID: 2946eb65c362
Revises: bc8138efc906
Create Date: 2026-04-15 12:15:53.063689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2946eb65c362'
down_revision: Union[str, Sequence[str], None] = 'bc8138efc906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_class', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(), nullable=True))
    op.add_column('suppliers', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'city')
    op.drop_column('clients', 'city')
    op.drop_column('accounts', 'account_class')
    # ### end Alembic commands ###
