"""add_city_to_clients_suppliers

Revision ID: 61bcb9d189d3
Revises: 1eda23ffa80d
Create Date: 2026-03-28 12:01:41.025637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bcb9d189d3'
down_revision: Union[str, Sequence[str], None] = '1eda23ffa80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
